"""The built-in exercise library.

Tuple layout:
``(name, name_ar, muscle_group, equipment, difficulty, type, tracking,
   secondary_muscles, rest_seconds, instructions)``
"""

from __future__ import annotations

from app.models.enums import (
    Difficulty as D,
    Equipment as E,
    ExerciseType as T,
    MuscleGroup as M,
    TrackingType as K,
)

EXERCISES: list[tuple] = [
    # --- chest ---------------------------------------------------------
    ("Barbell Bench Press", "ضغط البار المسطح", M.CHEST, E.BARBELL, D.INTERMEDIATE, T.STRENGTH,
     K.WEIGHT_REPS, [M.SHOULDERS, M.ARMS], 180,
     ["Lie flat with your eyes under the bar and set your feet.",
      "Grip just wider than shoulder width and pull your shoulder blades together.",
      "Lower the bar to mid-chest under control.",
      "Press back to straight arms without letting your ribs flare."]),
    ("Incline Dumbbell Press", "ضغط الدمبل المائل", M.CHEST, E.DUMBBELL, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [M.SHOULDERS, M.ARMS], 120,
     ["Set the bench to about 30 degrees.",
      "Start with the dumbbells at chest level, elbows slightly tucked.",
      "Press up and slightly together, then lower slowly."]),
    ("Dumbbell Bench Press", "ضغط الدمبل المسطح", M.CHEST, E.DUMBBELL, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [M.SHOULDERS, M.ARMS], 120, []),
    ("Push-Up", "تمرين الضغط", M.CHEST, E.BODYWEIGHT, D.BEGINNER, T.STRENGTH,
     K.REPS_ONLY, [M.SHOULDERS, M.ARMS, M.CORE], 60,
     ["Set your hands slightly wider than your shoulders.",
      "Keep a straight line from head to heels.",
      "Lower until your chest is just off the floor, then press back up."]),
    ("Cable Chest Fly", "تفتيح الكابل", M.CHEST, E.CABLE, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [M.SHOULDERS], 75, []),
    ("Chest Press Machine", "جهاز ضغط الصدر", M.CHEST, E.MACHINE, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [M.SHOULDERS, M.ARMS], 90, []),
    ("Dips", "الغطس", M.CHEST, E.BODYWEIGHT, D.INTERMEDIATE, T.STRENGTH,
     K.REPS_ONLY, [M.ARMS, M.SHOULDERS], 120, []),
    ("Decline Barbell Press", "ضغط البار المنحدر", M.CHEST, E.BARBELL, D.INTERMEDIATE,
     T.STRENGTH, K.WEIGHT_REPS, [M.ARMS], 150, []),

    # --- back ----------------------------------------------------------
    ("Deadlift", "الرفعة الميتة", M.BACK, E.BARBELL, D.ADVANCED, T.STRENGTH,
     K.WEIGHT_REPS, [M.LEGS, M.CORE], 240,
     ["Set the bar over mid-foot and grip just outside your shins.",
      "Take the slack out of the bar and set a flat back.",
      "Push the floor away and stand tall, keeping the bar close.",
      "Return the bar along the same path."]),
    ("Pull-Up", "العقلة", M.BACK, E.BODYWEIGHT, D.INTERMEDIATE, T.STRENGTH,
     K.REPS_ONLY, [M.ARMS], 150, []),
    ("Lat Pulldown", "سحب أمامي", M.BACK, E.CABLE, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [M.ARMS], 90, []),
    ("Barbell Row", "تجديف البار", M.BACK, E.BARBELL, D.INTERMEDIATE, T.STRENGTH,
     K.WEIGHT_REPS, [M.ARMS, M.CORE], 150, []),
    ("Seated Cable Row", "تجديف الكابل", M.BACK, E.CABLE, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [M.ARMS], 90, []),
    ("Single-Arm Dumbbell Row", "تجديف دمبل بذراع واحدة", M.BACK, E.DUMBBELL, D.BEGINNER,
     T.STRENGTH, K.WEIGHT_REPS, [M.ARMS], 90, []),
    ("Romanian Deadlift", "الرفعة الرومانية", M.BACK, E.BARBELL, D.INTERMEDIATE, T.STRENGTH,
     K.WEIGHT_REPS, [M.LEGS], 150, []),
    ("Chin-Up", "عقلة بقبضة معكوسة", M.BACK, E.BODYWEIGHT, D.INTERMEDIATE, T.STRENGTH,
     K.REPS_ONLY, [M.ARMS], 150, []),
    ("Face Pull", "سحب للوجه", M.BACK, E.CABLE, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [M.SHOULDERS], 60, []),
    ("Inverted Row", "تجديف معكوس", M.BACK, E.BODYWEIGHT, D.BEGINNER, T.STRENGTH,
     K.REPS_ONLY, [M.ARMS], 90, []),

    # --- shoulders -------------------------------------------------------
    ("Overhead Press", "ضغط الكتف بالبار", M.SHOULDERS, E.BARBELL, D.INTERMEDIATE, T.STRENGTH,
     K.WEIGHT_REPS, [M.ARMS, M.CORE], 180, []),
    ("Dumbbell Shoulder Press", "ضغط الكتف بالدمبل", M.SHOULDERS, E.DUMBBELL, D.BEGINNER,
     T.STRENGTH, K.WEIGHT_REPS, [M.ARMS], 120, []),
    ("Lateral Raise", "رفرفة جانبية", M.SHOULDERS, E.DUMBBELL, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [], 60,
     ["Hold the dumbbells at your sides with a soft bend in the elbows.",
      "Raise out to shoulder height, leading with the elbows.",
      "Lower slowly — this one is about control, not load."]),
    ("Rear Delt Fly", "رفرفة خلفية", M.SHOULDERS, E.DUMBBELL, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [M.BACK], 60, []),
    ("Arnold Press", "ضغط أرنولد", M.SHOULDERS, E.DUMBBELL, D.INTERMEDIATE, T.STRENGTH,
     K.WEIGHT_REPS, [M.ARMS], 120, []),
    ("Cable Lateral Raise", "رفرفة كابل", M.SHOULDERS, E.CABLE, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [], 60, []),
    ("Upright Row", "تجديف عمودي", M.SHOULDERS, E.BARBELL, D.INTERMEDIATE, T.STRENGTH,
     K.WEIGHT_REPS, [M.ARMS], 90, []),
    ("Pike Push-Up", "ضغط الهرم", M.SHOULDERS, E.BODYWEIGHT, D.INTERMEDIATE, T.STRENGTH,
     K.REPS_ONLY, [M.ARMS], 90, []),

    # --- arms ------------------------------------------------------------
    ("Barbell Curl", "مرجحة البار", M.ARMS, E.BARBELL, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [], 75, []),
    ("Dumbbell Curl", "مرجحة الدمبل", M.ARMS, E.DUMBBELL, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [], 60, []),
    ("Hammer Curl", "مرجحة مطرقة", M.ARMS, E.DUMBBELL, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [], 60, []),
    ("Triceps Pushdown", "دفع الترايسبس", M.ARMS, E.CABLE, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [], 60, []),
    ("Overhead Triceps Extension", "تمديد الترايسبس", M.ARMS, E.DUMBBELL, D.BEGINNER,
     T.STRENGTH, K.WEIGHT_REPS, [], 60, []),
    ("Close-Grip Bench Press", "ضغط بقبضة ضيقة", M.ARMS, E.BARBELL, D.INTERMEDIATE, T.STRENGTH,
     K.WEIGHT_REPS, [M.CHEST, M.SHOULDERS], 120, []),
    ("Preacher Curl", "مرجحة الواعظ", M.ARMS, E.MACHINE, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [], 75, []),
    ("Bench Dip", "غطس على المقعد", M.ARMS, E.BODYWEIGHT, D.BEGINNER, T.STRENGTH,
     K.REPS_ONLY, [M.CHEST], 60, []),
    ("Cable Curl", "مرجحة الكابل", M.ARMS, E.CABLE, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [], 60, []),

    # --- legs ------------------------------------------------------------
    ("Back Squat", "السكوات الخلفي", M.LEGS, E.BARBELL, D.INTERMEDIATE, T.STRENGTH,
     K.WEIGHT_REPS, [M.CORE, M.BACK], 210,
     ["Set the bar on your upper back and brace hard.",
      "Sit down between your hips, keeping your knees tracking over your toes.",
      "Descend to at least parallel, then drive the floor away."]),
    ("Front Squat", "السكوات الأمامي", M.LEGS, E.BARBELL, D.ADVANCED, T.STRENGTH,
     K.WEIGHT_REPS, [M.CORE], 180, []),
    ("Goblet Squat", "سكوات الكأس", M.LEGS, E.DUMBBELL, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [M.CORE], 90, []),
    ("Leg Press", "ضغط الأرجل", M.LEGS, E.MACHINE, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [], 120, []),
    ("Bulgarian Split Squat", "سكوات بلغاري", M.LEGS, E.DUMBBELL, D.INTERMEDIATE, T.STRENGTH,
     K.WEIGHT_REPS, [M.CORE], 120, []),
    ("Walking Lunge", "الاندفاع المتحرك", M.LEGS, E.DUMBBELL, D.BEGINNER, T.STRENGTH,
     K.REPS_ONLY, [M.CORE], 90, []),
    ("Leg Curl", "ثني الأرجل", M.LEGS, E.MACHINE, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [], 75, []),
    ("Leg Extension", "تمديد الأرجل", M.LEGS, E.MACHINE, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [], 75, []),
    ("Hip Thrust", "رفع الحوض", M.LEGS, E.BARBELL, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [M.CORE], 120, []),
    ("Standing Calf Raise", "رفع السمانة واقفاً", M.LEGS, E.MACHINE, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [], 60, []),
    ("Air Squat", "سكوات بوزن الجسم", M.LEGS, E.BODYWEIGHT, D.BEGINNER, T.STRENGTH,
     K.REPS_ONLY, [M.CORE], 60, []),
    ("Glute Bridge", "جسر المؤخرة", M.LEGS, E.BODYWEIGHT, D.BEGINNER, T.STRENGTH,
     K.REPS_ONLY, [M.CORE], 60, []),
    ("Kettlebell Swing", "أرجحة الكيتل بيل", M.LEGS, E.KETTLEBELL, D.INTERMEDIATE, T.PLYOMETRIC,
     K.REPS_ONLY, [M.BACK, M.CORE], 90, []),
    ("Step-Up", "الصعود على الصندوق", M.LEGS, E.DUMBBELL, D.BEGINNER, T.STRENGTH,
     K.REPS_ONLY, [M.CORE], 90, []),

    # --- core ------------------------------------------------------------
    ("Plank", "البلانك", M.CORE, E.BODYWEIGHT, D.BEGINNER, T.STRENGTH,
     K.DURATION, [M.SHOULDERS], 60,
     ["Set your elbows under your shoulders.",
      "Squeeze your glutes and brace as if about to be pushed.",
      "Hold a straight line — stop the set when your hips drop."]),
    ("Hanging Leg Raise", "رفع الأرجل معلقاً", M.CORE, E.BODYWEIGHT, D.INTERMEDIATE, T.STRENGTH,
     K.REPS_ONLY, [], 75, []),
    ("Cable Crunch", "كرنش الكابل", M.CORE, E.CABLE, D.BEGINNER, T.STRENGTH,
     K.WEIGHT_REPS, [], 60, []),
    ("Russian Twist", "اللف الروسي", M.CORE, E.BODYWEIGHT, D.BEGINNER, T.STRENGTH,
     K.REPS_ONLY, [], 45, []),
    ("Dead Bug", "الحشرة الميتة", M.CORE, E.BODYWEIGHT, D.BEGINNER, T.STRENGTH,
     K.REPS_ONLY, [], 45, []),
    ("Side Plank", "بلانك جانبي", M.CORE, E.BODYWEIGHT, D.BEGINNER, T.STRENGTH,
     K.DURATION, [], 45, []),
    ("Ab Wheel Rollout", "عجلة البطن", M.CORE, E.OTHER, D.ADVANCED, T.STRENGTH,
     K.REPS_ONLY, [M.SHOULDERS], 75, []),
    ("Mountain Climber", "تسلق الجبل", M.CORE, E.BODYWEIGHT, D.BEGINNER, T.PLYOMETRIC,
     K.DURATION, [M.CARDIO], 45, []),
    ("Superman Hold", "تمرين سوبرمان", M.CORE, E.BODYWEIGHT, D.BEGINNER, T.STRENGTH,
     K.DURATION, [M.BACK], 45, []),

    # --- cardio ----------------------------------------------------------
    ("Treadmill Run", "الجري على السير", M.CARDIO, E.CARDIO_MACHINE, D.BEGINNER, T.CARDIO,
     K.DISTANCE, [M.LEGS], 60, []),
    ("Outdoor Run", "الجري في الخارج", M.CARDIO, E.BODYWEIGHT, D.BEGINNER, T.CARDIO,
     K.DISTANCE, [M.LEGS], 60, []),
    ("Stationary Bike", "الدراجة الثابتة", M.CARDIO, E.CARDIO_MACHINE, D.BEGINNER, T.CARDIO,
     K.DURATION, [M.LEGS], 60, []),
    ("Rowing Machine", "جهاز التجديف", M.CARDIO, E.CARDIO_MACHINE, D.BEGINNER, T.CARDIO,
     K.DISTANCE, [M.BACK, M.LEGS], 60, []),
    ("Jump Rope", "نط الحبل", M.CARDIO, E.OTHER, D.BEGINNER, T.CARDIO,
     K.DURATION, [M.LEGS], 45, []),
    ("Stair Climber", "جهاز الدرج", M.CARDIO, E.CARDIO_MACHINE, D.BEGINNER, T.CARDIO,
     K.DURATION, [M.LEGS], 60, []),
    ("Burpee", "البيربي", M.CARDIO, E.BODYWEIGHT, D.INTERMEDIATE, T.PLYOMETRIC,
     K.REPS_ONLY, [M.CHEST, M.LEGS], 60, []),
    ("Incline Walk", "المشي المائل", M.CARDIO, E.CARDIO_MACHINE, D.BEGINNER, T.CARDIO,
     K.DURATION, [M.LEGS], 60, []),

    # --- mobility --------------------------------------------------------
    ("Hip Flexor Stretch", "إطالة مثنية الورك", M.MOBILITY, E.BODYWEIGHT, D.BEGINNER, T.STRETCH,
     K.DURATION, [M.LEGS], 30, []),
    ("Thoracic Rotation", "دوران الصدري", M.MOBILITY, E.BODYWEIGHT, D.BEGINNER, T.MOBILITY,
     K.REPS_ONLY, [M.BACK], 30, []),
    ("Cat-Cow", "القطة والبقرة", M.MOBILITY, E.BODYWEIGHT, D.BEGINNER, T.MOBILITY,
     K.REPS_ONLY, [M.BACK], 30, []),
    ("Hamstring Stretch", "إطالة أوتار الركبة", M.MOBILITY, E.BODYWEIGHT, D.BEGINNER, T.STRETCH,
     K.DURATION, [M.LEGS], 30, []),
    ("Shoulder Dislocates", "تحرير الكتف", M.MOBILITY, E.RESISTANCE_BAND, D.BEGINNER,
     T.MOBILITY, K.REPS_ONLY, [M.SHOULDERS], 30, []),
    ("90/90 Hip Switch", "تبديل الورك 90/90", M.MOBILITY, E.BODYWEIGHT, D.BEGINNER, T.MOBILITY,
     K.REPS_ONLY, [M.LEGS], 30, []),

    # --- full body / bands ------------------------------------------------
    ("Band Row", "تجديف بالحبل المطاطي", M.BACK, E.RESISTANCE_BAND, D.BEGINNER, T.STRENGTH,
     K.REPS_ONLY, [M.ARMS], 60, []),
    ("Band Chest Press", "ضغط الصدر بالحبل", M.CHEST, E.RESISTANCE_BAND, D.BEGINNER, T.STRENGTH,
     K.REPS_ONLY, [M.ARMS], 60, []),
    ("Band Pull-Apart", "فتح الحبل المطاطي", M.SHOULDERS, E.RESISTANCE_BAND, D.BEGINNER,
     T.STRENGTH, K.REPS_ONLY, [M.BACK], 45, []),
    ("Band Squat", "سكوات بالحبل", M.LEGS, E.RESISTANCE_BAND, D.BEGINNER, T.STRENGTH,
     K.REPS_ONLY, [M.CORE], 60, []),
    ("Turkish Get-Up", "النهوض التركي", M.FULL_BODY, E.KETTLEBELL, D.ADVANCED, T.STRENGTH,
     K.REPS_ONLY, [M.CORE, M.SHOULDERS], 120, []),
    ("Farmer's Carry", "حمل المزارع", M.FULL_BODY, E.DUMBBELL, D.BEGINNER, T.STRENGTH,
     K.DURATION, [M.CORE, M.BACK], 90, []),
    ("Clean and Press", "النتر والضغط", M.FULL_BODY, E.BARBELL, D.ADVANCED, T.OLYMPIC,
     K.WEIGHT_REPS, [M.LEGS, M.SHOULDERS], 180, []),
    ("Thruster", "الثراستر", M.FULL_BODY, E.DUMBBELL, D.INTERMEDIATE, T.STRENGTH,
     K.WEIGHT_REPS, [M.LEGS, M.SHOULDERS], 120, []),
]
