"""initial schema

Revision ID: 003997ee72c5
Revises: 
Create Date: 2026-09-19 13:12:43.618135
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401 - referenced by rendered JSONB columns
from sqlalchemy.dialects import postgresql  # noqa: F401 - JSONB variant

import app.db.types  # noqa: F401 - GUID/JSON column types

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('avatar_key', sa.String(length=512), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('oauth_provider', sa.String(length=24), nullable=True),
    sa.Column('oauth_subject', sa.String(length=255), nullable=True),
    sa.Column('subscription_tier', sa.String(length=16), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('oauth_provider', 'oauth_subject', name='uq_users_oauth_identity')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index('ix_users_role_status', ['role', 'status'], unique=False)

    op.create_table('ai_conversations',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_conversations'))
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_last_message_at'), ['last_message_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('ai_generations',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('request_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('result_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_generations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_generations'))
    )
    with op.batch_alter_table('ai_generations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_generations_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_generations_status'), ['status'], unique=False)
        batch_op.create_index('ix_ai_generations_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_generations_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('actor_id', app.db.types.GUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=320), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_action_created', ['action', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)

    op.create_table('body_measurements',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('recorded_on', sa.Date(), nullable=False),
    sa.Column('measurement_type', sa.String(length=24), nullable=False),
    sa.Column('custom_label', sa.String(length=60), nullable=True),
    sa.Column('value_cm', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_body_measurements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body_measurements')),
    sa.UniqueConstraint('user_id', 'recorded_on', 'measurement_type', 'custom_label', name='uq_body_measurements_user_day_type')
    )
    with op.batch_alter_table('body_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_measurements_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_body_measurements_user_type_date', ['user_id', 'measurement_type', 'recorded_on'], unique=False)

    op.create_table('body_weights',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('recorded_on', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('body_fat_percent', sa.Float(), nullable=True),
    sa.Column('muscle_mass_kg', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_body_weights_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body_weights')),
    sa.UniqueConstraint('user_id', 'recorded_on', name='uq_body_weights_user_day')
    )
    with op.batch_alter_table('body_weights', schema=None) as batch_op:
        batch_op.create_index('ix_body_weights_user_date', ['user_id', 'recorded_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_weights_user_id'), ['user_id'], unique=False)

    op.create_table('daily_nutrition',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('logged_on', sa.Date(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('water_ml', sa.Integer(), nullable=False),
    sa.Column('calorie_target', sa.Integer(), nullable=True),
    sa.Column('protein_target_g', sa.Integer(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_nutrition_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_nutrition')),
    sa.UniqueConstraint('user_id', 'logged_on', name='uq_daily_nutrition_user_day')
    )
    with op.batch_alter_table('daily_nutrition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_nutrition_user_id'), ['user_id'], unique=False)

    op.create_table('exercises',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('name_ar', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('muscle_group', sa.String(length=24), nullable=False),
    sa.Column('secondary_muscles', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('equipment', sa.String(length=24), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('exercise_type', sa.String(length=16), nullable=False),
    sa.Column('default_tracking_type', sa.String(length=24), nullable=False),
    sa.Column('default_rest_seconds', sa.Integer(), nullable=False),
    sa.Column('is_unilateral', sa.Boolean(), nullable=False),
    sa.Column('video_url', sa.String(length=512), nullable=True),
    sa.Column('image_key', sa.String(length=512), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', app.db.types.GUID(), nullable=True),
    sa.Column('search_text', sa.String(length=512), nullable=False),
    sa.Column('aliases', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_exercises_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises'))
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_equipment'), ['equipment'], unique=False)
        batch_op.create_index('ix_exercises_group_equipment', ['muscle_group', 'equipment'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_muscle_group'), ['muscle_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_name'), ['name'], unique=False)
        batch_op.create_index('ix_exercises_search', ['search_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_slug'), ['slug'], unique=True)

    op.create_table('foods',
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('name_ar', sa.String(length=180), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('calories_per_100g', sa.Float(), nullable=False),
    sa.Column('protein_per_100g', sa.Float(), nullable=False),
    sa.Column('carbs_per_100g', sa.Float(), nullable=False),
    sa.Column('fat_per_100g', sa.Float(), nullable=False),
    sa.Column('fiber_per_100g', sa.Float(), nullable=False),
    sa.Column('sugar_per_100g', sa.Float(), nullable=True),
    sa.Column('sodium_mg_per_100g', sa.Float(), nullable=True),
    sa.Column('serving_options', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('default_serving_grams', sa.Float(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('search_text', sa.String(length=400), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_foods_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_foods'))
    )
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foods_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_foods_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_foods_name'), ['name'], unique=False)
        batch_op.create_index('ix_foods_search', ['search_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_foods_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_foods_user_name', ['user_id', 'name'], unique=False)

    op.create_table('habits',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('frequency', sa.String(length=16), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=24), nullable=True),
    sa.Column('active_weekdays', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('reminder_time', sa.String(length=5), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_habits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habits'))
    )
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habits_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_habits_user_id'), ['user_id'], unique=False)

    op.create_table('meals',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('logged_on', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_saved_template', sa.Boolean(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=False),
    sa.Column('total_protein_g', sa.Float(), nullable=False),
    sa.Column('total_carbs_g', sa.Float(), nullable=False),
    sa.Column('total_fat_g', sa.Float(), nullable=False),
    sa.Column('total_fiber_g', sa.Float(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meals')),
    sa.UniqueConstraint('user_id', 'client_uuid', name='uq_meals_user_client_uuid')
    )
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meals_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index('ix_meals_user_date', ['user_id', 'logged_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_meals_user_id'), ['user_id'], unique=False)

    op.create_table('notification_preferences',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('workout_reminders', sa.Boolean(), nullable=False),
    sa.Column('workout_reminder_time', sa.String(length=5), nullable=False),
    sa.Column('goal_reminders', sa.Boolean(), nullable=False),
    sa.Column('habit_reminders', sa.Boolean(), nullable=False),
    sa.Column('progress_reminders', sa.Boolean(), nullable=False),
    sa.Column('weekly_summary', sa.Boolean(), nullable=False),
    sa.Column('personal_record_alerts', sa.Boolean(), nullable=False),
    sa.Column('rest_timer_alerts', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_notification_preferences_user_id'))
    )
    op.create_table('notifications',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('deep_link', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'read_at'], unique=False)

    op.create_table('progress_photos',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('taken_on', sa.Date(), nullable=False),
    sa.Column('pose', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=512), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_progress_photos_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progress_photos'))
    )
    with op.batch_alter_table('progress_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_photos_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_photos_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_progress_photos_user_taken', ['user_id', 'taken_on'], unique=False)

    op.create_table('subscriptions',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('platform', sa.String(length=24), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('sync_operations',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('operation', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('server_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sync_operations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_operations')),
    sa.UniqueConstraint('user_id', 'client_uuid', name='uq_sync_operations_user_client')
    )
    with op.batch_alter_table('sync_operations', schema=None) as batch_op:
        batch_op.create_index('ix_sync_operations_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_operations_user_id'), ['user_id'], unique=False)

    op.create_table('usage_records',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('metric', sa.String(length=48), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usage_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_records'))
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index('ix_usage_records_lookup', ['user_id', 'day', 'metric'], unique=True)
        batch_op.create_index(batch_op.f('ix_usage_records_user_id'), ['user_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('current_weight_kg', sa.Float(), nullable=True),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('unit_system', sa.String(length=16), nullable=False),
    sa.Column('primary_goal', sa.String(length=32), nullable=False),
    sa.Column('fitness_level', sa.String(length=16), nullable=False),
    sa.Column('activity_level', sa.String(length=16), nullable=False),
    sa.Column('workout_location', sa.String(length=16), nullable=False),
    sa.Column('available_equipment', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('training_days_per_week', sa.Integer(), nullable=False),
    sa.Column('preferred_session_minutes', sa.Integer(), nullable=False),
    sa.Column('daily_calorie_target', sa.Integer(), nullable=True),
    sa.Column('daily_protein_target_g', sa.Integer(), nullable=True),
    sa.Column('daily_carbs_target_g', sa.Integer(), nullable=True),
    sa.Column('daily_fat_target_g', sa.Integer(), nullable=True),
    sa.Column('daily_fiber_target_g', sa.Integer(), nullable=True),
    sa.Column('daily_water_target_ml', sa.Integer(), nullable=False),
    sa.Column('targets_are_manual', sa.Boolean(), nullable=False),
    sa.Column('default_rest_seconds', sa.Integer(), nullable=False),
    sa.Column('ai_context_opt_in', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_profiles_user_id'))
    )
    op.create_table('user_sessions',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=320), nullable=True),
    sa.Column('push_token', sa.String(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', app.db.types.GUID(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_refresh_token_hash'), ['refresh_token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_user_sessions_user_revoked', ['user_id', 'revoked_at'], unique=False)

    op.create_table('verification_tokens',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_verification_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_tokens'))
    )
    with op.batch_alter_table('verification_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_verification_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_verification_tokens_user_purpose', ['user_id', 'purpose'], unique=False)

    op.create_table('water_logs',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('logged_on', sa.Date(), nullable=False),
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_water_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_water_logs')),
    sa.UniqueConstraint('user_id', 'client_uuid', name='uq_water_logs_user_client_uuid')
    )
    with op.batch_alter_table('water_logs', schema=None) as batch_op:
        batch_op.create_index('ix_water_logs_user_date', ['user_id', 'logged_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_water_logs_user_id'), ['user_id'], unique=False)

    op.create_table('workout_programs',
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('source_template_id', app.db.types.GUID(), nullable=True),
    sa.Column('goal', sa.String(length=32), nullable=True),
    sa.Column('difficulty', sa.String(length=16), nullable=True),
    sa.Column('location', sa.String(length=16), nullable=True),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('equipment_needed', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('generated_by_ai', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_programs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_programs'))
    )
    with op.batch_alter_table('workout_programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_programs_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_programs_is_template'), ['is_template'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_programs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_programs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_workout_programs_user_status', ['user_id', 'status'], unique=False)

    op.create_table('ai_messages',
    sa.Column('conversation_id', app.db.types.GUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('safety_redirect', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], name=op.f('fk_ai_messages_conversation_id_ai_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_messages'))
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('exercise_media',
    sa.Column('exercise_id', app.db.types.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('external_url', sa.String(length=512), nullable=True),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercise_media_exercise_id_exercises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_media'))
    )
    with op.batch_alter_table('exercise_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_media_exercise_id'), ['exercise_id'], unique=False)

    op.create_table('favorite_foods',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('food_id', app.db.types.GUID(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_favorite_foods_food_id_foods'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorite_foods_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorite_foods')),
    sa.UniqueConstraint('user_id', 'food_id', name='uq_favorite_foods')
    )
    with op.batch_alter_table('favorite_foods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_foods_user_id'), ['user_id'], unique=False)

    op.create_table('habit_logs',
    sa.Column('habit_id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('logged_on', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], name=op.f('fk_habit_logs_habit_id_habits'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_habit_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habit_logs')),
    sa.UniqueConstraint('habit_id', 'logged_on', name='uq_habit_logs_habit_day')
    )
    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_logs_habit_id'), ['habit_id'], unique=False)
        batch_op.create_index('ix_habit_logs_user_date', ['user_id', 'logged_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_habit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('meal_items',
    sa.Column('meal_id', app.db.types.GUID(), nullable=False),
    sa.Column('food_id', app.db.types.GUID(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=180), nullable=False),
    sa.Column('serving_label', sa.String(length=80), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_meal_items_food_id_foods'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_meal_items_meal_id_meals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_items'))
    )
    with op.batch_alter_table('meal_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_items_meal_id'), ['meal_id'], unique=False)

    op.create_table('user_goals',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('goal_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exercise_id', app.db.types.GUID(), nullable=True),
    sa.Column('measurement_type', sa.String(length=24), nullable=True),
    sa.Column('start_value', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('is_decreasing', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_user_goals_exercise_id_exercises'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_goals'))
    )
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_goals_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_goals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_goals_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_user_goals_user_status', ['user_id', 'status'], unique=False)

    op.create_table('workout_days',
    sa.Column('program_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_rest_day', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['workout_programs.id'], name=op.f('fk_workout_days_program_id_workout_programs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_days'))
    )
    with op.batch_alter_table('workout_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_days_program_id'), ['program_id'], unique=False)

    op.create_table('workout_day_exercises',
    sa.Column('day_id', app.db.types.GUID(), nullable=False),
    sa.Column('exercise_id', app.db.types.GUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('target_reps_min', sa.Integer(), nullable=True),
    sa.Column('target_reps_max', sa.Integer(), nullable=True),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('target_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('target_distance_m', sa.Float(), nullable=True),
    sa.Column('target_rpe', sa.Float(), nullable=True),
    sa.Column('target_rir', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('tracking_type', sa.String(length=24), nullable=False),
    sa.Column('superset_group', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['workout_days.id'], name=op.f('fk_workout_day_exercises_day_id_workout_days'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_workout_day_exercises_exercise_id_exercises'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_day_exercises'))
    )
    with op.batch_alter_table('workout_day_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_day_exercises_day_id'), ['day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_day_exercises_exercise_id'), ['exercise_id'], unique=False)

    op.create_table('workout_sessions',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('program_id', app.db.types.GUID(), nullable=True),
    sa.Column('day_id', app.db.types.GUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('perceived_effort', sa.Integer(), nullable=True),
    sa.Column('bodyweight_kg', sa.Float(), nullable=True),
    sa.Column('total_volume_kg', sa.Float(), nullable=False),
    sa.Column('total_sets', sa.Integer(), nullable=False),
    sa.Column('total_reps', sa.Integer(), nullable=False),
    sa.Column('estimated_calories', sa.Integer(), nullable=True),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['workout_days.id'], name=op.f('fk_workout_sessions_day_id_workout_days'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['workout_programs.id'], name=op.f('fk_workout_sessions_program_id_workout_programs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_sessions')),
    sa.UniqueConstraint('user_id', 'client_uuid', name='uq_workout_sessions_user_client_uuid')
    )
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_sessions_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_workout_sessions_user_started', ['user_id', 'started_at'], unique=False)
        batch_op.create_index('ix_workout_sessions_user_status', ['user_id', 'status'], unique=False)

    op.create_table('personal_records',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('exercise_id', app.db.types.GUID(), nullable=False),
    sa.Column('record_type', sa.String(length=24), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', app.db.types.GUID(), nullable=True),
    sa.Column('set_id', app.db.types.GUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_personal_records_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], name=op.f('fk_personal_records_session_id_workout_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_personal_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_records'))
    )
    with op.batch_alter_table('personal_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personal_records_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index('ix_personal_records_lookup', ['user_id', 'exercise_id', 'record_type'], unique=False)
        batch_op.create_index('ix_personal_records_user_achieved', ['user_id', 'achieved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_personal_records_user_id'), ['user_id'], unique=False)

    op.create_table('workout_session_exercises',
    sa.Column('session_id', app.db.types.GUID(), nullable=False),
    sa.Column('exercise_id', app.db.types.GUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('tracking_type', sa.String(length=24), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('superset_group', sa.Integer(), nullable=True),
    sa.Column('target_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('replaced_exercise_id', app.db.types.GUID(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_workout_session_exercises_exercise_id_exercises'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], name=op.f('fk_workout_session_exercises_session_id_workout_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_session_exercises'))
    )
    with op.batch_alter_table('workout_session_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_session_exercises_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_session_exercises_session_id'), ['session_id'], unique=False)

    op.create_table('workout_sets',
    sa.Column('session_exercise_id', app.db.types.GUID(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('set_type', sa.String(length=16), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('rir', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('estimated_1rm_kg', sa.Float(), nullable=True),
    sa.Column('volume_kg', sa.Float(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['workout_session_exercises.id'], name=op.f('fk_workout_sets_session_exercise_id_workout_session_exercises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_sets')),
    sa.UniqueConstraint('session_exercise_id', 'set_number', name='uq_workout_sets_number')
    )
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_sets_session_exercise_id'), ['session_exercise_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_sets_session_exercise_id'))

    op.drop_table('workout_sets')
    with op.batch_alter_table('workout_session_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_session_exercises_session_id'))
        batch_op.drop_index(batch_op.f('ix_workout_session_exercises_exercise_id'))

    op.drop_table('workout_session_exercises')
    with op.batch_alter_table('personal_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personal_records_user_id'))
        batch_op.drop_index('ix_personal_records_user_achieved')
        batch_op.drop_index('ix_personal_records_lookup')
        batch_op.drop_index(batch_op.f('ix_personal_records_exercise_id'))

    op.drop_table('personal_records')
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_workout_sessions_user_status')
        batch_op.drop_index('ix_workout_sessions_user_started')
        batch_op.drop_index(batch_op.f('ix_workout_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_workout_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_workout_sessions_is_deleted'))

    op.drop_table('workout_sessions')
    with op.batch_alter_table('workout_day_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_day_exercises_exercise_id'))
        batch_op.drop_index(batch_op.f('ix_workout_day_exercises_day_id'))

    op.drop_table('workout_day_exercises')
    with op.batch_alter_table('workout_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_days_program_id'))

    op.drop_table('workout_days')
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.drop_index('ix_user_goals_user_status')
        batch_op.drop_index(batch_op.f('ix_user_goals_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_goals_status'))
        batch_op.drop_index(batch_op.f('ix_user_goals_is_deleted'))

    op.drop_table('user_goals')
    with op.batch_alter_table('meal_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_items_meal_id'))

    op.drop_table('meal_items')
    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_logs_user_id'))
        batch_op.drop_index('ix_habit_logs_user_date')
        batch_op.drop_index(batch_op.f('ix_habit_logs_habit_id'))

    op.drop_table('habit_logs')
    with op.batch_alter_table('favorite_foods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_foods_user_id'))

    op.drop_table('favorite_foods')
    with op.batch_alter_table('exercise_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_media_exercise_id'))

    op.drop_table('exercise_media')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_messages_conversation_id'))

    op.drop_table('ai_messages')
    with op.batch_alter_table('workout_programs', schema=None) as batch_op:
        batch_op.drop_index('ix_workout_programs_user_status')
        batch_op.drop_index(batch_op.f('ix_workout_programs_user_id'))
        batch_op.drop_index(batch_op.f('ix_workout_programs_status'))
        batch_op.drop_index(batch_op.f('ix_workout_programs_is_template'))
        batch_op.drop_index(batch_op.f('ix_workout_programs_is_deleted'))

    op.drop_table('workout_programs')
    with op.batch_alter_table('water_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_water_logs_user_id'))
        batch_op.drop_index('ix_water_logs_user_date')

    op.drop_table('water_logs')
    with op.batch_alter_table('verification_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_verification_tokens_user_purpose')
        batch_op.drop_index(batch_op.f('ix_verification_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_verification_tokens_token_hash'))

    op.drop_table('verification_tokens')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_user_sessions_user_revoked')
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_refresh_token_hash'))

    op.drop_table('user_sessions')
    op.drop_table('user_profiles')
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_records_user_id'))
        batch_op.drop_index('ix_usage_records_lookup')

    op.drop_table('usage_records')
    with op.batch_alter_table('sync_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_operations_user_id'))
        batch_op.drop_index('ix_sync_operations_user_created')

    op.drop_table('sync_operations')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('progress_photos', schema=None) as batch_op:
        batch_op.drop_index('ix_progress_photos_user_taken')
        batch_op.drop_index(batch_op.f('ix_progress_photos_user_id'))
        batch_op.drop_index(batch_op.f('ix_progress_photos_is_deleted'))

    op.drop_table('progress_photos')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meals_user_id'))
        batch_op.drop_index('ix_meals_user_date')
        batch_op.drop_index(batch_op.f('ix_meals_is_deleted'))

    op.drop_table('meals')
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habits_user_id'))
        batch_op.drop_index(batch_op.f('ix_habits_is_deleted'))

    op.drop_table('habits')
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_index('ix_foods_user_name')
        batch_op.drop_index(batch_op.f('ix_foods_user_id'))
        batch_op.drop_index('ix_foods_search')
        batch_op.drop_index(batch_op.f('ix_foods_name'))
        batch_op.drop_index(batch_op.f('ix_foods_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_foods_barcode'))

    op.drop_table('foods')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_slug'))
        batch_op.drop_index('ix_exercises_search')
        batch_op.drop_index(batch_op.f('ix_exercises_name'))
        batch_op.drop_index(batch_op.f('ix_exercises_muscle_group'))
        batch_op.drop_index(batch_op.f('ix_exercises_is_public'))
        batch_op.drop_index(batch_op.f('ix_exercises_is_deleted'))
        batch_op.drop_index('ix_exercises_group_equipment')
        batch_op.drop_index(batch_op.f('ix_exercises_equipment'))
        batch_op.drop_index(batch_op.f('ix_exercises_created_by_id'))

    op.drop_table('exercises')
    with op.batch_alter_table('daily_nutrition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_nutrition_user_id'))

    op.drop_table('daily_nutrition')
    with op.batch_alter_table('body_weights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_weights_user_id'))
        batch_op.drop_index('ix_body_weights_user_date')

    op.drop_table('body_weights')
    with op.batch_alter_table('body_measurements', schema=None) as batch_op:
        batch_op.drop_index('ix_body_measurements_user_type_date')
        batch_op.drop_index(batch_op.f('ix_body_measurements_user_id'))

    op.drop_table('body_measurements')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index('ix_audit_logs_action_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_generations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_generations_user_id'))
        batch_op.drop_index('ix_ai_generations_user_created')
        batch_op.drop_index(batch_op.f('ix_ai_generations_status'))
        batch_op.drop_index(batch_op.f('ix_ai_generations_kind'))

    op.drop_table('ai_generations')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_last_message_at'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_is_deleted'))

    op.drop_table('ai_conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role_status')
        batch_op.drop_index(batch_op.f('ix_users_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
